### ISSUE TITLE
SONAME differs between autoconf and CMake builds

### ISSUE THREAD

**Issue by StefanBruens** [HEASARC/cfitsio#21]
The CMake build uses the MAJOR version for the soversion:

https://github.com/HEASARC/cfitsio/blob/f220e6e2c570f19228609ee081f735df0ddb204b/CMakeLists.txt#L291

The autoconf build uses a distinct version:

https://github.com/HEASARC/cfitsio/blob/f220e6e2c570f19228609ee081f735df0ddb204b/configure.ac#L17-L21

Please adjust the SOVERSION in the CMake build to match the one from autoconf.

**Comment by bryanirby** [comment]
Thanks for the report, my apologies for overlooking that.  The main/master branch has been updated and given a new tag (cfitsio4_4_1_20240617).

**Comment by StefanBruens** [comment]
As far as I can see the SOVERSION is still "4"
https://github.com/HEASARC/cfitsio/blob/1e5dc1b1766808a8f974fb0236e3ab3032b9b062/CMakeLists.txt#L291

**Comment by bryanirby** [comment]
You're right, I misread your report as pointing out that the 4.4.1 updates hadn't changed the micro version from 0 to 1 in the CMakeLists.txt.  The mismatched SOVERSION from CMakeLists.txt is a separate, longer-standing issue.  We'll fix this for the upcoming 4.5.0 release.
