### ISSUE TITLE
ffpmsg

### ISSUE THREAD

**Issue by jprenderg** [HEASARC/cfitsio#26]
Is there somewhere I can find the .h and .c files for ffpmsg?

**Comment by esabol** [comment]
The source code for `ffpmsg()` is in [fitscore.c](https://github.com/HEASARC/cfitsio/blob/6ba7e3319c02c0831c860c37212f37f37a726cce/fitscore.c#L678), and the prototype for it is in [fitsio.h](https://github.com/HEASARC/cfitsio/blob/6ba7e3319c02c0831c860c37212f37f37a726cce/fitsio.h#L815).

**Comment by jprenderg** [comment]
Thank you.
________________________________

**Comment by jprenderg** [comment]
One more question. Where can I find declarations and source code for:

fits_get_img_type
fits_get_img_dim
fits_get_tile_dim
fits_get_img_size
fits_get_img_sizell

Thanks,
Joe
________________________________

**Comment by esabol** [comment]
https://github.com/HEASARC/cfitsio/blob/56640a39c59148b5143d8dd0833cce6a88a55d8c/longnam.h#L230

There's a search input box at the top of the GitHub web page that will search the repository.

**Comment by jprenderg** [comment]
Thanks, I hadn't realized that.
________________________________
