### ISSUE TITLE
CMake: redundant "lib"

### ISSUE THREAD

**Issue by kmilos** [HEASARC/cfitsio#28]
Since 4.5.0 there is a redundant "lib" directory created when installing some artifacts:
```
/lib/lib/cfitsio-4.5.0/
/lib/lib/cfitsio-4.5.0/cfitsio-config.cmake
/lib/lib/cfitsio-4.5.0/cfitsio-config-version.cmake
/lib/lib/pkgconfig/
/lib/lib/pkgconfig/cfitsio.pc
```
This seems to be regression introduced in https://github.com/HEASARC/cfitsio/commit/29eccbb61fc213a61dd1e63c53e9f910a14cba5e trying to address #23.

Edit: [Arch workaround](https://gitlab.archlinux.org/archlinux/packaging/packages/cfitsio/-/blob/96ad31aa368305ba1e9914d1d24e973cf9f6f707/PKGBUILD#L22), [Fedora patch](https://src.fedoraproject.org/rpms/mingw-cfitsio/blob/f41/f/cfitsio_cmake.patch)...

**Comment by kmilos** [comment]
Btw, there's seldom need to override and construct `LIB_DESTINATION` (and other install dirs) by hand like that.

[GNUInstallDirs `CMAKE_INSTALL_LIBDIR`](CMAKE_INSTALL_<dir>) (and others) should be correct (almost) all the time, even on multi-arch systems.

**Comment by bryanirby** [comment]
Hi @kmilos, thanks for the report. I've checked a fix for this into the develop branch. We'll look into revising the use of LIB_DESTINATION et al. in future development.
