### ISSUE TITLE
Modified sha of published tarballs

### ISSUE THREAD

**Issue by AbrilRBS** [HEASARC/cfitsio#31]
Hi!

In Conan Center Index we got a report that source downloads were breaking in https://github.com/conan-io/conan-center-index/issues/25712 for this library due to a sha256 mismatch in the published sources over at https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/. 

After a bit more digging, and having access to the old tar files, I found that there was no real change besides the size of the tarball.

As shown in the linked issue:
```
~/Downloads $ shasum -a 256 old.tar.gz 
ef9881973ecb9fe55732a4c1bb5ca96e63b624728f6319556939e0fe25f495e8  old.tar.gz
~/Downloads $ shasum -a 256 new.tar.gz 
eba53d1b3f6e345632bb09a7b752ec7ced3d63ec5153a848380f3880c5d61889  new.tar.gz
~/Downloads $ diff -q --no-dereference new/ old/
~/Downloads $ 
```

I'm writing just to see if you could provide a bit more insight into this before we fix the checksums on our end. Was this just a recompression of the files for smaller size footprint? We would love to have a bit more context before blindly updating the checksums, thanks! :)

**Comment by bryanirby** [comment]
Hi @AbrilRBS -

Could you be more specific about which files you're referring to at the FTP site?  I see that your 'new.tar.gz' appears to refer to cfitsio-4.2.0.tar.gz,

eba53d1b3f6e345632bb09a7b752ec7ced3d63ec5153a848380f3880c5d61889  cfitsio-4.2.0.tar.gz

but I'm not seeing any files that match your old.tar.gz.  For clarification, the current release is 4.5.0, and the "cfitsio_latest.tar.gz" file is just a link to the tar file with that number:

e4854fc3365c1462e493aa586bfaa2f3d0bb8c20b75a524955db64c27427ce09  cfitsio-4.5.0.tar.gz
e4854fc3365c1462e493aa586bfaa2f3d0bb8c20b75a524955db64c27427ce09  cfitsio_latest.tar.gz

Thanks,
Bryan

**Comment by AbrilRBS** [comment]
Yes sorry, I should have clarified further.

This would be for the specified 4.2.0 version, but note that this happens for all of the currently available versions:

- The PR https://github.com/conan-io/conan-center-index/pull/19781 in September 13th 2023 built all the supported versions at that point.
- Conan has a backup source feature that allows us to store the source files and serve them from our remote if they ever go missing from upstream.
- At that point, 4.2.0's checksum was `ef9881973ecb9fe55732a4c1bb5ca96e63b624728f6319556939e0fe25f495e8` as can be seen in the [`conandata.yml` file](https://github.com/AbrilRBS/conan-center-index/blob/c6f10619723555b796b4e6f2327dc58a15b70178/recipes/cfitsio/all/conandata.yml#L4), and as no errors were reported, it means that https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-4.2.0.tar.gz at least at that point in time had `ef9881973ecb9fe55732a4c1bb5ca96e63b624728f6319556939e0fe25f495e8` as its checksum
- That same PR uploaded https://c3i.jfrog.io/artifactory/conan-center-backup-sources/ef9881973ecb9fe55732a4c1bb5ca96e63b624728f6319556939e0fe25f495e8 as our backup of the sources, which is where I got the "old" file from
- The reporting user in the linked issue notes that:

> This issue is very recent as everything worked well 24 hours ago.

So it seems like at some point in the past, maybe as close as a few days ago, https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-4.2.0.tar.gz went from the old checksum to the new one we're now seeing, but as explained above, the contents of the file seem to be unmodified.

Note that this is also the case for all other available versions - For example 4.4.0 was added to Conan Center Index in https://github.com/conan-io/conan-center-index/pull/23252 on June 11th with a valid checksum of `c42bd609151c0b0d7c4f3578d425ae7aaa9afa4828cab35c0accea588e290c29` but today we're seeing `95900cf95ae760839e7cb9678a7b2fad0858d6ac12234f934bd1cb6bfc246ba9` for that same file


Let me know if this helps :)

**Comment by c181gordon** [comment]
Hi @AbrilRBS,

The checksum differences you're seeing are most likely due to a recent configuration change made to our web servers.  They no longer issue the http header information string that explicitly identifies gzipped files.  (I believe this was done to prevent some browsers from automatically performing the unzipping of the tarball without also removing the '.gz' extension.)  Therefore it's likely that your old checksum was actually for the unzipped version of the tarball -- we did a checksum of the unzipped cfitsio-4.2.0.tar file and found it matched your old value.  When you download the files now and perform a checksum, it will be for the gzipped version of the tarball.

**Comment by AbrilRBS** [comment]
Thanks a lot for the extra info, it was super helpful. Closing this as solved now that we've updated the checksums to the new ones, thanks everyone! :)
